### ISSUE TITLE
Tasks: supports globs for patterns

### ISSUE THREAD

**Issue by DenysVuika** [DenysVuika/affected#21]
Support globs for patterns when declaring the tasks

**before**:

```yml
tasks:
- name: lint
  description: Runs eslint for all affected files (example)
  patterns:
  - '*.ts'
  - '*.tsx'
  - '*.js'
  - '*.jsx'
```

**after**:

```yml
tasks:
- name: lint
  description: Runs eslint for all affected files (example)
  patterns:
  - '*.{ts,tsx,js,jsx}'
```
